spring:
  datasource:
    url: jdbc:sqlite:./data/book_exchange.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080